###
### Register a new user successfully /api/auth - 201
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth
Content-Type: application/json
Accept: application/json

{
  "email": "newuser@example.com",
  "password": "Password123!"
}

> {%
    client.test("User created successfully", function () {
        client.assert(response.status === 201, "Response is not 201");
        client.assert(response.body.token != null, "Token not returned");
        client.global.set("bidder_token", response.body.token);
    });
%}

###
### Try to create a user with the same email again /api/auth - 409
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth
Content-Type: application/json
Accept: application/json

{
  "email": "newuser@example.com",
  "password": "AnotherPassword123!"
}

> {%
    client.test("User creation conflict", function () {
        client.assert(response.status === 409, "Response is not 409");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/already exists/i), "No 'already exists' message");
    });
%}

###
### Register user with invalid email /api/auth - 400
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth
Content-Type: application/json
Accept: application/json

{
  "email": "not-an-email",
  "password": "Password123!"
}

> {%
    client.test("Invalid email error", function () {
        client.assert(response.status === 400, "Response is not 400");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/Invalid email/i), "No invalid email message");
    });
%}

###
### Register user with short password /api/auth - 400
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth
Content-Type: application/json
Accept: application/json

{
  "email": "shortpass@example.com",
  "password": "short"
}

> {%
    client.test("Short password error", function () {
        client.assert(response.status === 400, "Response is not 400");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/Password must be at least 8 characters/i), "No short password message");
    });
%}

###
### Login with correct credentials /api/auth/tokens - 200
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "newuser@example.com",
  "password": "Password123!"
}

> {%
    client.test("Login successful", function () {
        client.assert(response.status === 200, "Response is not 200");
        client.assert(response.body.token != null, "Token not returned");
        client.global.set("login_token", response.body.token);
    });
%}

###
### Login user with invalid email /api/auth - 400
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "not-an-email",
  "password": "Password123!"
}

> {%
    client.test("Invalid email error", function () {
        client.assert(response.status === 400, "Response is not 400");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/Invalid email/i), "No invalid email message");
    });
%}

###
### Login user with short password /api/auth - 400
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "shortpass@example.com",
  "password": "short"
}

> {%
    client.test("Short password error", function () {
        client.assert(response.status === 400, "Response is not 400");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/Password must be at least 8 characters/i), "No short password message");
    });
%}

###
### Login with wrong password /api/auth/tokens - 401
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "newuser@example.com",
  "password": "WrongPassword!"
}

> {%
    client.test("Unauthorized for wrong password", function () {
        client.assert(response.status === 401, "Response is not 401");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/Invalid password/i), "No invalid password message");
    });
%}

###
### Login with non-existing user /api/auth/tokens - 404
###
POST {{protocol}}//{{host}}:{{port}}/{{default_path}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "no-such-user@example.com",
  "password": "Password123!"
}

> {%
    client.test("User not found error", function () {
        client.assert(response.status === 404, "Response is not 404");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/not found/i), "No 'not found' message");
    });
%}
