### Get all categories successfully /api/categories - 200
GET {{protocol}}//{{host}}:{{port}}/{{default_path}}/categories
Accept: application/json

> {%
    client.test("Retrieve categories successfully", function () {
        client.assert(response.status === 200, "Response is not 200");
        client.assert(response.body != null, "Response body is null");
        client.assert(response.body.domains != null, "Domains not returned");
        client.assert(response.body.licenses != null, "Licenses not returned");
        client.assert(response.body.languages != null, "Languages not returned");
        client.assert(Array.isArray(response.body.domains), "Domains is not an array");
        client.assert(Array.isArray(response.body.licenses), "Licenses is not an array");
        client.assert(Array.isArray(response.body.languages), "Languages is not an array");
        client.assert(response.body.domains.length > 0, "Domains array is empty");
        client.assert(response.body.licenses.length > 0, "Licenses array is empty");
        client.assert(response.body.languages.length > 0, "Languages array is empty");
    });
%}

### Get categories with invalid JSON format /api/categories - 400
GET {{protocol}}//{{host}}:{{port}}/{{default_path}}/categories
Content-Type: application/json
Accept: application/json

{
  "invalidJsonField": "value",
  "invalidKey"
}

> {%
    client.test("Invalid JSON format error on categories", function () {
        client.assert(response.status === 400, "Response is not 400");
        client.assert(response.body.error != null, "Error not returned");
        client.assert(response.body.error.message.match(/Invalid JSON format/i), "No 'Invalid JSON format' message");
    });
%}
